const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas fit shirt',
      slug: 'adidas-slim-shirt',
      category: 'shirts',
      image: '/images/p2.jpg',
      price: 150,
      countInStock: 7,
      brand: 'Adidas',
      rating: 2,
      numReviews: 129,
      description: 'low quality shirt',
    },
    {
      name: 'Nike Slim pants',
      slug: 'nike-slim-pants',
      category: 'pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality pants',
    },
    {
      name: 'Adidas Fit pants',
      slug: 'adidas-slim-pants',
      category: 'pants',
      image: '/images/p4.jpg',
      price: 250,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pants',
    },
  ],
};
export default data;
